# Description: TCP and UDP bandwidth performance measurement tool
# URL: https://iperf.fr/
# License: BSD

name=iperf
version=3.1.3
release=1
source=(https://iperf.fr/download/source/iperf-$version-source.tar.gz)
depends=(util-linux)

build() {
   cd $name-$version

   ./configure --prefix=/usr  \
               --host=$HOST   \
               --build=$BUILD \
               --disable-static

   make -j$JOBS

   make DESTDIR=$PKG install

   fix_la_files $PKG
}
