# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gst-plugins-good
version=1.0.4
release=1
source=(http://gstreamer.freedesktop.org/src/gst-plugins-good/$name-$version.tar.xz)
depends=(gstreamer gst-plugins-base libpng libjpeg orc)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-oss4 \
               --disable-oss \

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/locale

   # Fix libtool files
   fix_la_files $PKG
}
