# Description: Open source connection mananger
# URL: https://01.org/connman
# License: GPLv2

name=connman
version=1.28
release=1
source=(http://www.kernel.org/pub/linux/network/connman/$name-$version.tar.xz
        connman.service)
depends=(glib dbus iptables gnutls readline ncurses wpa_supplicant systemd)

build() {
   cd $name-$version

   LIBS=-lncurses \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc \
               --enable-ethernet \
               --enable-loopback \
               --enable-client \
               --enable-tools \
               --enable-datafiles \
               --enable-shared \
               --enable-wifi \
               --enable-bluetooth \
               --disable-hh2serial-gps \
               --disable-ofono \
               --disable-openconnect \
               --disable-openvpn \
               --disable-vpnc \
               --disable-l2tp \
               --disable-pptp \
               --disable-iospm \
               --disable-test \
               --disable-tist \
               --disable-nmcompat \
               --disable-polkit \
               --with-systemdunitdir=/etc/systemd/system \
               ac_cv_path_WPASUPPLICANT=/usr/sbin/wpa_supplicant

   make -j $JOBS
   make DESTDIR=$PKG install

   install -D -m 0755 client/connmanctl $PKG/usr/bin/connmanctl
   install -D -m 0644 src/main.conf $PKG/etc/connman/main.conf
   install -D -m 0644 $SRC/connman.service $PKG/etc/systemd/system/connman.service
}
