# Description: Open source connection mananger
# URL: http://connman.net/

name=connman
version=git-bf87298c
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.xz
        connman.service)
depends=(glib dbus iptables gnutls readline wpa_supplicant)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-ethernet \
               --enable-loopback \
               --enable-client \
               --enable-tools \
               --enable-datafiles \
               --enable-shared \
               --enable-wifi \
               --disable-bluetooth \
               --disable-hh2serial-gps \
               --disable-ofono \
               --disable-openconnect \
               --disable-openvpn \
               --disable-vpnc \
               --disable-l2tp \
               --disable-pptp \
               --disable-iwmx \
               --disable-iospm \
               --disable-test \
               --disable-tist \
               --disable-nmcompat \
               --disable-polkit \
               ac_cv_path_WPASUPPLICANT=/usr/sbin/wpa_supplicant

   make -j $JOBS
   make DESTDIR=$PKG install

   install -D -m 0755 client/connmanctl $PKG/usr/bin/connmanctl
   install -D $SRC/connman.service $PKG/etc/systemd/system/connman.service
}
