# Description: Open source connection mananger
# URL: http://connman.net/

name=connman
version=1.6
release=1
source=(http://www.kernel.org/pub/linux/network/$name/$name-$version.tar.xz)
depends=(glib dbus iptables gnutls)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-ethernet \
               --disable-wifi \
               --disable-bluetooth \
               --disable-hh2serial-gps \
               --disable-ofono \
               --disable-openconnect \
               --disable-openvpn \
               --disable-vpnc \
               --disable-l2tp \
               --disable-pptp \
               --disable-iwmx \
               --disable-iospm \
               --enable-test \
               --disable-tist \
               --disable-nmcompat \
               --disable-polkit \
               --enable-loopback \
               --enable-client \
               --enable-tools \
               --enable-datafiles \
               --enable-shared

   make -j $JOBS
   make DESTDIR=$PKG install

   # FIXME: Add systemd init script
   rm -r $PKG/etc
}
