# Description: filesystem utilities for use with the ext2 filesystem
# URL: http://e2fsprogs.sourceforge.net/
# License: GPLv2

name=e2fsprogs
version=1.42.13
release=1
source=(https://www.kernel.org/pub/linux/kernel/people/tytso/$name/v$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
