# Description: A low-level cryptographic library
# URL: http://www.lysator.liu.se/~nisse/nettle
# License: LGPLv2.1

name=nettle
version=3.4
release=1
source=(ftp://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)
depends=(gmp)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share
   rm $PKG/usr/lib/*.a

   # Fix libtool files
   fix_la_files $PKG
}
