# Description: libnetfilter_acct is the userspace library providing interface to extended accounting infrastructure. 
# URL: http://www.netfilter.org/projects/libnetfilter_acct/index.html
# License: GPLv2.1

name=libnetfilter_acct
version=1.0.3
release=1
source=(http://www.netfilter.org/projects/$name/files/$name-$version.tar.bz2)
depends=(libmnl)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-shared

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
