# Description: Firmware for TI wifi/bluetooth chips
# URL: https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git
# License: TI-TSPA

name=ti-connectivity-firmware
version=git7d0c7a8
release=1
source=(http://www.buildgear.org/mirror/$name-$version.tar.gz)

build() {
   mkdir -p $PKG/lib/firmware
   cp -r $SRC/* $PKG/lib/firmware
}

