# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gstreamer-0.10
version=0.10.36
release=1
source=(http://gstreamer.freedesktop.org/src/gstreamer/$name.36.tar.xz)
depends=(glib)

build() {
   cd $name.36

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
	           --disable-{examples,tests,loadsave}

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{gtk-doc,locale}

   # Fix libtool files
   fix_la_files $PKG
}

