# Description: libva is an implementation of VA-API for Linux
# URL: http://freedesktop.org/wiki/Software/vaapi

name=libva
version=2.1.0
release=1
source=(https://github.com/intel/libva/releases/download/$version/$name-$version.tar.bz2)
depends=(libdrm)

build() {
   cd $name-$version

   ./configure --prefix=/usr  \
               --host=$HOST   \
               --build=$BUILD

   make -j$JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
