# Description: Is a userspace library providing an API to packets that have been queued by the kernel packet filter.
# URL: http://www.netfilter.org/projects/libnetfilter_queue/index.html
# License: GPLv2

name=libnetfilter_queue
version=1.0.3
release=1
source=(http://www.netfilter.org/projects/$name/files/$name-$version.tar.bz2)
depends=(libnfnetlink libmnl)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-shared

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
