# Description: Library of PNG support functions
# URL: http://www.ijg.org/

name=libjpeg
version=9
release=1
source=(http://www.ijg.org/files/jpegsrc.v$version.tar.gz
        boolean.patch)

build() {

   cd jpeg-$version

   patch -p2 < $SRC/boolean.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
