# Description: Library of PNG support functions
# URL: http://www.ijg.org/

name=libjpeg
version=8d
release=1
source=(http://www.ijg.org/files/jpegsrc.v$version.tar.gz)

build() {
   cd jpeg-$version

   ./configure --prefix=/usr \
               --build=$BUILD \
               --host=$HOST 

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
