# Description: Library for JPEG image compression
# URL: http://www.infai.org/jpeg/
# License: LIBJPEG

name=libjpeg
version=9c
release=1
source=(http://www.ijg.org/files/jpegsrc.v9c.tar.gz)

build() {

   cd jpeg-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
