# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org
# License: LGPLv2

name=gst-plugins-ugly
version=1.10.4
release=1
source=(http://gstreamer.freedesktop.org/src/$name/$name-$version.tar.xz)
depends=(gstreamer gst-plugins-base)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls \
               --disable-gtk-doc

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/gtk-doc

   # Fix libtool files
   fix_la_files $PKG
}
