# Description: Mobile broadband settings for different service providers
# URL: https://git.gnome.org/browse/mobile-broadband-provider-info
# License: PD

name=mobile-broadband-provider-info
version=git-eaf82e5f14
release=1
source=(http://buildgear.org/mirror/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make
   make DESTDIR=$PKG install
}
