# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gstreamer
version=1.0.7
release=1
source=(http://gstreamer.freedesktop.org/src/gstreamer/$name-$version.tar.xz)
depends=glib

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{gtk-doc,locale}

   # Fix libtool files
   fix_la_files $PKG
}

