# Description: The GNU Debugger (GDB)
# URL: http://sources.redhat.com/gdb/

name=gdb
version=7.6.1
release=1
source=(ftp://ftp.gnu.org/gnu/$name/$name-$version.tar.bz2)
depends=ncurses

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/info
}
