# Description: The GNU Debugger (GDB)
# URL: http://sources.redhat.com/gdb
# License: GPLv3 GPLv2 GFDL PD BSD LGPLv2

name=gdb
version=7.12
release=1
source=(ftp://ftp.gnu.org/gnu/$name/$name-$version.tar.xz)
depends=ncurses

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG -C gdb install

   rm -rf $PKG/usr/share/info

   fix_la_files $PKG
}
