# Description: Perfect hash function generator
# URL: http://www.gnu.org/software/gperf
# License: GPLv3

name=gperf
version=3.0.4
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{doc,info}
}

