# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org
# License: LGPLv2

name=gst-plugins-bad-0.10
version=0.10.23
release=1
source=(http://gstreamer.freedesktop.org/src/${name%-*}/${name%-*}-$version.tar.xz)
depends=(gstreamer-0.10 gst-plugins-base-0.10)

build() {
   cd ${name%-*}-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-{directsound,direct3d,directdraw} \
               --disable-{apple_media,osx_video} \
               --disable-avc \
               --disable-quicktime \
               --disable-shm \
               --disable-vcd \
               --disable-assrender \
               --disable-voamrwbenc \
               --disable-apexsink \
               --disable-cdaudio \
               --disable-celt \
               --disable-cog \
               --disable-curl \
               --disable-dc1394 \
               --disable-decklink \
               --disable-dirac \
               --disable-dts \
               --disable-divx \
               --disable-resindvd \
               --disable-flite \
               --disable-gsm \
               --disable-kate \
               --disable-ladspa \
               --disable-lv2 \
               --disable-libmms \
               --disable-linsys \
               --disable-modplug \
               --disable-mimic \
               --disable-mplex \
               --disable-musepack \
               --disable-musicbrainz \
               --disable-mythtv \
               --disable-nas \
               --disable-neon \
               --disable-ofa \
               --disable-openal \
               --disable-opencv \
               --disable-opus \
               --disable-rsvg \
               --disable-timidity \
               --disable-teletextdec \
               --disable-wildmidi \
               --disable-sdl \
               --disable-sndfile \
               --disable-soundtouch \
               --disable-spc \
               --disable-gme \
               --disable-swfdec \
               --disable-xvid \
               --disable-dvb \
               --disable-wininet \
               --disable-acm \
               --disable-schro \
               --disable-zbar \
               --disable-rtmp \
               --disable-spandsp \
               --disable-gsettings

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/locale

   # Fix libtool files
   fix_la_files $PKG
}

