# Description: ALSA libraries
# URL: http://www.alsa-project.org
# License: LGPLv2

name=alsa-lib
version=1.1.6
release=1
source=(ftp://ftp.alsa-project.org/pub/lib/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-python \
               --without-debug

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
