# Description: ALSA libraries
# URL: http://www.alsa-project.org

name=alsa-lib
version=1.0.25
release=1
source=(ftp://ftp.alsa-project.org/pub/lib/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-python 

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
