# Description: ALSA libraries
# URL: http://www.alsa-project.org

name=alsa-lib
version=1.0.27.2
release=1
source=(http://alsa.cybermirror.org/lib/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-python \
               --without-debug

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
