# Description: GNU Midnight Commander
# URL: http://www.midnight-commander.org
# License: GPLv2

name=mc
version=4.8.17
release=1
source=(http://ftp.midnight-commander.org/mc-$version.tar.xz)
depends=(ncurses glib)

build () {
   cd $name-$version

   ./configure --host=$HOST \
               --build=$BUILD \
               --prefix=/usr \
               --mandir=/usr/share/man \
               --libexecdir=/usr/lib \
               --disable-nls \
               --with-screen=ncurses \
               LIBS=-ltinfo

    make
    make DESTDIR=$PKG install

    rm $PKG/usr/lib/mc/*/README*
}
