# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org

name=gst-plugins-bad
version=1.0.5
release=1
source=(http://gstreamer.freedesktop.org/src/$name/$name-$version.tar.xz)
depends=(gstreamer gst-plugins-base orc)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/locale

   # Fix libtool files
   fix_la_files $PKG
}
