# Description: strace is a system call tracer
# URL: https://strace.io
# License: BSD

name=strace
version=4.22
release=1
source=(https://github.com/strace/strace/releases/download/v$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST   \
               --prefix=/usr

   make -j$JOBS
   make DESTDIR=$PKG install
}
