# Description: strace is a system call tracer
# URL: http://sourceforge.net/projects/strace
# License: BSD

name=strace
version=4.10
release=1
source=(http://downloads.sourceforge.net/project/$name/$name/$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST   \
               --prefix=/usr

   make -j$JOBS
   make DESTDIR=$PKG install
}
