# Description: TIFF Library and Utilities
# URL: http://www.libtiff.org/

name=libtiff
version=4.0.2
release=1
source=(ftp://ftp.remotesensing.org/pub/libtiff/tiff-$version.tar.gz)
depends=(zlib libjpeg)

build() {
   cd tiff-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}

