# Description: TIFF Library and Utilities
# URL: http://www.libtiff.org
# License: LIBTIFF

name=libtiff
version=4.0.7
release=1
source=(http://download.osgeo.org/$name/tiff-$version.tar.gz)
depends=(zlib libjpeg)

build() {
   cd tiff-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}

