# Description: A library for configuring and customizing font access
# URL: http://fontconfig.org
# License: MIT

name=fontconfig
version=2.11.0
release=1
source=(http://fontconfig.org/release/$name-$version.tar.gz)
depends=(freetype expat)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --sysconfdir=/etc \
               --localstatedir=/var \
               --disable-docs

   make -j $JOBS
   make DESTDIR=$PKG install

   # Install prebuilt docs
   mkdir -p $PKG/usr/share/man/man{1,3,5}
   install -v -dm755 \
      $PKG/usr/share/{man/man{3,5},doc/fontconfig-$version/fontconfig-devel}
   install -v -m644 fc-*/*.1          $PKG/usr/share/man/man1
   install -v -m644 doc/*.3           $PKG/usr/share/man/man3
   install -v -m644 doc/fonts-conf.5  $PKG/usr/share/man/man5

   # Enabling autohinting by default
   pushd $PKG/etc/fonts/conf.d
   ln -s ../../../usr/share/fontconfig/conf.avail/10-autohint.conf
   popd

   rm $PKG/etc/fonts/conf.d/README
   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
