# Description: Valgrind is an instrumentation framework for building dynamic analysis tools
# URL: http://valgrind.org
# License: GPLv2

name=valgrind
version=3.10.1
release=1
source=(http://valgrind.org/downloads/$name-$version.tar.bz2
        host-type-arm.patch
        valgrind-3.10.1-glibc_2.21-1.patch)

build() {
   cd $name-$version

   patch -p1 -i $SRC/host-type-arm.patch

   ./autogen.sh NOCONFIGURE=1

   patch -p1 -i $SRC/valgrind-3.10.1-glibc_2.21-1.patch

   ./configure --prefix=/usr  \
               --host=$HOST   \
               --build=$BUILD \

   make -j$JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/doc

}
