# Description: Library for constructing graphs of media-handling components
# URL: http://gstreamer.freedesktop.org
# License: LGPLv2

name=gst-plugins-base
version=1.4.3
release=1
source=(http://gstreamer.freedesktop.org/src/gst-plugins-base/$name-$version.tar.xz)
depends=(gstreamer alsa-lib orc)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-ogg \
               --disable-vorbis

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{gtk-doc,locale}

   # Fix libtool files
   fix_la_files $PKG
}

