# Description: Fast console MPEG Audio Player and decoder library
# URL: http://www.mpg123.de
# License: LGPLv2.1

name=mpg123
version=1.23.3
release=1
source=(http://downloads.sourceforge.net/project/$name/$name/$version/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --prefix=/usr  \
               --host=$HOST   \
               --build=$BUILD

   make -j$JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
