# Description: ALSA utils
# URL: http://www.alsa-project.org
# License: GPLv2

name=alsa-utils
version=1.0.29
release=1
source=(http://alsa.cybermirror.org/utils/$name-$version.tar.bz2)
depends=(alsa-lib dialog systemd)

build() {
   cd $name-$version

   LDFLAGS="-L$SYSROOT/usr/lib" \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-alsaconf \
               --with-udev-rules-dir=/usr/lib/udev/rules.d \
               --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --disable-nls

   # alsactl_init.7 is generated using xmlto, which we don't have
   touch alsactl/alsactl_init.7

   make -j $JOBS
   make DESTDIR=$PKG install

   rm $PKG/usr/share/man/man7/alsactl_init.7
   rmdir $PKG/usr/share/man/man7
}
