# Description: Is a userspace library providing a programming interface (API) to the in-kernel connection tracking state table. 
# URL: http://www.netfilter.org/projects/libnetfilter_conntrack/
# License: GPLv2+

name=libnetfilter_conntrack
version=1.0.6
release=1
source=(http://www.netfilter.org/projects/$name/files/$name-$version.tar.bz2)
depends=(libnfnetlink libmnl)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-shared

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
