# Description: The really simple TTY terminal application
# URL: http://gotty.io
# License: GPLv2

name=gotty
version=1.2
release=1
source=(https://github.com/$name/$name/releases/download/v$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
