# Description: XML library version 2
# URL: http://xmlsoft.org
# License: MIT

name=libxml2
version=2.9.2
release=1
source=(ftp://xmlsoft.org/libxml2/$name-$version.tar.gz)
depends=zlib

build () {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --without-python

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/{doc,gtk-doc}

   # Fix libtool files
   fix_la_files $PKG
}
