# Description: libnet provides a portable framework for low-level network packet construction.
# URL: http://sourceforge.net/projects/libnet-dev/
# License: BSD

name=libnet
version=1.2-rc3
release=1
source=(http://sourceforge.net/projects/$name-dev/files/$name-$version.tar.gz)

build() {
   cd libnet-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

