# Description: utilities for making and checking MS-DOS FAT filesystems
# URL: https://github.com/dosfstools/dosfstools
# License: GPLv2

name=dosfstools
version=4.0
release=1
source=(https://github.com/$name/$name/releases/download/v$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
