# Description: OProfile is a system-wide profiler for Linux systems, capable of profiling all running code at low overhead.
# URL: http://oprofile.sourceforge.net/news
# License: GPLv2

name=oprofile
version=1.1.0
release=1
source=(http://downloads.sourceforge.net/$name/$name-$version.tar.gz)
depends=(popt which linux)

build() {
   cd $name-$version

   ./configure --prefix=/usr     \
               --build=$BUILD    \
               --host=$HOST      \
               --disable-static  \
               --with-kernel=$NATIVE_SYSROOT/usr/src/linux

   make -j$JOBS
   make DESTDIR=$PKG install

   fix_la_files $PKG
}
