# Description: Network Time Protocol software
# URL: http://www.ntp.org
# License: MIT BSD GPLv2

name=ntp
version=4.2.8p1
release=1
source=(http://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/$name-$version.tar.gz
        ntp.conf ntpd.service)
depends=(openssl libcap)

build () {
   cd $name-$version
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-sntp \
               --with-crypto \
               --enable-debugging=no \
               --enable-ntpdate-step \
               --enable-parse-clocks \
               --enable-all-clocks \
               --with-yielding-select=yes
   make -j $JOBS
   make DESTDIR=$PKG install

   install -Dm644 $SRC/ntp.conf $PKG/etc/ntp.conf
   install -Dm644 $SRC/ntpd.service $PKG/etc/systemd/system/ntpd.service
   
   #Open port used by NTP
   echo "ntp 123/udp" >> $PKG/etc/services

}
