# Description: Open Source Telephony
# URL: https://01.org/ofono
# License: GPLv2

name=ofono
version=1.19
release=1
source=(https://www.kernel.org/pub/linux/network/ofono/$name-$version.tar.xz)
depends=(systemd glib dbus mobile-broadband-provider-info)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-bluetooth

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
