# Description: Lets users edit command lines as they are typed in
# URL: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html

name=readline
version=6.2
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz \
        readline62-001 readline62-002 inputrc \
        http://ftp.gnu.org/gnu/readline/readline-6.2-patches/readline62-003 \
        http://ftp.gnu.org/gnu/readline/readline-6.2-patches/readline62-004)
depends=(ncurses)

build() {
   cd $name-$version

   cat $SRC/readline62-??? | patch -p0

   # Don't use rpath for linking the shared libs
   sed -i '117s/-Wl,-rpath,$(libdir)//' support/shobj-conf

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --with-curses

   make -j $JOBS SHLIB_LIBS=-lncurses
   make DESTDIR=$PKG install

   install -D -m 644 $SRC/inputrc $PKG/etc/inputrc
   rm -r $PKG/usr/share/info
}
