# Description: Lets users edit command lines as they are typed in
# URL: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
# License: GPLv3

name=readline
version=7.0
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.gz \
        inputrc)
depends=(ncurses)

build() {
   cd $name-$version

   # Don't use rpath for linking the shared libs
   sed -i '117s/-Wl,-rpath,$(libdir)//' support/shobj-conf

   bash_cv_wcwidth_broken=no \
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --with-curses

   make -j $JOBS SHLIB_LIBS=-lncurses
   make DESTDIR=$PKG install

   install -D -m 644 $SRC/inputrc $PKG/etc/inputrc

   # Cleanup
   rm -r $PKG/usr/share/{info,doc}
}
