# Description: XSL Transformations library
# URL: http://xmlsoft.org/XSLT

name=libxslt
version=1.1.28
release=1
source=(ftp://xmlsoft.org/libxml2/$name-$version.tar.gz
        cross_compilation.patch)
depends=libxml2

build() {
   cd $name-$version

   patch -p1 -i $SRC/cross_compilation.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --without-debug \
               --without-crypto \
               --without-python \
               --with-libxml-src=$SYSROOT/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
