# Description: XSL Transformations library
# URL: http://xmlsoft.org/XSLT

name=libxslt
version=1.1.26
release=1
source=(ftp://xmlsoft.org/libxml2/$name-$version.tar.gz \
        $name-$version.cross_compilation.patch)
depends=libxml2

build() {
   cd $name-$version

   patch -p1 -i $SRC/$name-$version.cross_compilation.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --without-debug \
               --without-crypto \
               --without-python \
               --with-libxml-src=$SYSROOT/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix .la files
   find $PKG -name "*.la" -exec sed -i -e "/dependency_libs/s; /usr; $SYSROOT/usr;g" {} \;
   find $PKG -name "*.la" -exec sed -i -e "/libdir/s;'/usr;'$SYSROOT/usr;g" {} \;
}
