# Description: Library for handling input devices
# URL: http://www.freedesktop.org/wiki/Software/libinput

name=libinput
version=1.10.7
release=1
source=(http://www.freedesktop.org/software/$name/$name-$version.tar.xz)
depends=(mtdev systemd libevdev)

build() {
    cd $name-$version

    meson build --prefix=/usr                 \
                --libdir=/usr/lib             \
                --cross-file=$CFG/$HOST.meson \
                -Dlibwacom=false              \
                -Ddebug-gui=false             \
                -Ddocumentation=false         \
                -Dtests=false

    ninja -C build -j $JOBS

    DESTDIR=$PKG \
    ninja -C build install
}
