# Description: A library that provides a secure layer over a reliable transport layer
# URL: http://www.gnu.org/software/gnutls
# License: GPLv3 LGPLv2

name=gnutls
version=3.2.18
release=1
source=(ftp://ftp.gnutls.org/gcrypt/gnutls/v3.2/$name-$version.tar.xz)
depends=(nettle)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-guile \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -rf $PKG/usr/share/{info,locale}

   # Fix libtool files
   fix_la_files $PKG
}
