# Description: A tool to trace the route of ip packets
# URL: http://traceroute.sourceforge.net
# License: GPLv2

name=traceroute
version=2.0.21
release=1
source=(http://downloads.sourceforge.net/project/$name/$name/$name-$version/$name-$version.tar.gz)

build() {
   cd $name-$version

   make -j $JOBS CROSS="$HOST-" LDFLAGS="-L../libsupp -s"
   make DESTDIR=$PKG prefix=/usr mandir=/usr/share/man install
}
