# Description: Official Linux Bluetooth protocol stack
# URL: https://www.bluez.org
# License: GPLv2+

name=bluez
version=5.13
release=1
source=(http://www.kernel.org/pub/linux/bluetooth/$name-$version.tar.xz)
depends=(systemd glib dbus readline libusb libical)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --enable-library \
               --enable-test

   make -j $JOBS
   make DESTDIR=$PKG install

   install -D $SRC/$name-$version/attrib/gatttool $PKG/usr/bin/gatttool

   # Fix libtool files
   fix_la_files $PKG
}
