# Description: Tracing control daemons, libraries and interfaces 
# URL: http://lttng.org
# License: LGPLv2 GPLv2

name=lttng-tools
version=2.8.1
release=1
source=(http://lttng.org/files/lttng-tools/$name-$version.tar.bz2 \
        lttng-tools_disable-tests.patch)
depends=(popt libuuid liburcu lttng-ust libxml2)

build() {
   cd $name-$version

   patch -p1 -i $SRC/lttng-tools_disable-tests.patch

   autoreconf --install
   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --with-xml-prefix=$SYSROOT/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}

check() {
   check_tool autoreconf
}
