# Description: Tracing control daemons, libraries and interfaces 
# URL: http://lttng.org
# License: LGPLv2 GPLv2

name=lttng-tools
version=2.5.3
release=1
source=(http://lttng.org/files/lttng-tools/$name-$version.tar.bz2)
depends=(popt libuuid liburcu lttng-ust libxml2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
