# Description: Secure, fast, compliant and very flexible web server
# URL: http://www.lighttpd.net
# License: BSD

name=lighttpd
version=1.4.49
release=1
source=(http://download.$name.net/$name/releases-1.4.x/$name-$version.tar.xz
        lighttpd-allow-uid-0.patch
        $name.conf
        $name.service)
depends=(pcre openssl bzip2)

build() {
    cd $name-$version

    patch -p1 -i $SRC/lighttpd-allow-uid-0.patch

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --libdir=/usr/lib/$name \
                --with-openssl \
                --with-pcre

    make -j $JOBS PCRE_LIB='-lpcre'
    make DESTDIR=$PKG install

    install -D -m 644 $SRC/$name.conf $PKG/etc/$name/$name.conf
    install -d $PKG/var/www/{htdocs,logs}
    install -d $PKG/var/run
    install -d $PKG/etc/ssl/certs
    install -d $PKG/etc/lighttpd/conf.d
    install -D -m 644 $SRC/$name.service $PKG/etc/systemd/system/$name.service
    touch $PKG/var/run/lighttpd.pid
    touch $PKG/etc/ssl/certs/lighttpd.pem
    chmod 0600 $PKG/etc/ssl/certs/lighttpd.pem

    # Fix libtool files
    fix_la_files $PKG
}

