# Description: Secure, fast, compliant and very flexible web server
# URL: http://www.lighttpd.net/

name=lighttpd
version=1.4.32
release=1
source=(http://download.$name.net/$name/releases-1.4.x/$name-$version.tar.bz2 \
        $name.conf
        $name.service
        root_user.patch)
depends=(libpcre openssl bzip2)

build() {
   cd $name-$version

   patch -p1 < $SRC/root_user.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libdir=/usr/lib/$name \
               --with-openssl \
               --with-pcre

   make -j $JOBS PCRE_LIB='-lpcre'
   make DESTDIR=$PKG install

   install -D -m 644 $SRC/$name.conf $PKG/etc/$name/$name.conf
   install -d $PKG/var/www/{htdocs,logs}
   install -d $PKG/var/run
   install -d $PKG/etc/ssl/certs
   install -D -m 644 $SRC/$name.service $PKG/etc/systemd/system/$name.service
   touch $PKG/var/run/lighttpd.pid
   touch $PKG/etc/ssl/certs/lighttpd.pem
   chmod 0600 $PKG/etc/ssl/certs/lighttpd.pem

   # Fix libtool files
   fix_la_files $PKG
}

