# Description: Tools to configure and manipulate wlan devices
# URL: http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html
# License: GPLv2

name=wireless_tools
version=29
release=1
source=(http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/$name.$version.tar.gz)

build() {
   cd $name.$version

   make -j $JOBS CC="$HOST-gcc"
   make PREFIX=$PKG/usr INSTALL_MAN=$PKG/usr/share/man install
}
