# Description: Libraries providing APIs to netlink protocol
# URL: http://www.infradead.org/~tgr/libnl
# License: LGPLv2

name=libnl
version=3.2.25
release=1
source=(https://ftp.osuosl.org/pub/blfs/conglomeration/$name/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-nls

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}

