# Description: i2c-tools package contains a heterogeneous set of I2C tools for Linux.
# URL: https://i2c.wiki.kernel.org/index.php/I2C_Tools
# License: GPLv2

name=i2c-tools
version=4.0
release=1
source=(https://mirrors.edge.kernel.org/pub/software/utils/$name/$name-$version.tar.xz)

build()
{
   cd $name-$version

   make CC=$HOST-gcc \
        prefix=/usr \
        sbindir=/usr/bin \
        DESTDIR=$PKG \
        install
}
