# Description: lm_sensors package provides user-space support for the hardware monitoring drivers in the Linux kernel.
# URL: http://www.lm-sensors.org/wiki/I2CTools
# License: GPLv2

name=lm-sensors
version=3.3.5
release=1
source=(http://dl.lm-sensors.org/$name/releases/lm_sensors-$version.tar.bz2 \
        http://www.linuxfromscratch.org/patches/blfs/svn/lm_sensors-$version-upstream_fixes-1.patch)

build()
{
   cd lm_sensors-$version

   patch -p 1 -i $SRC/lm_sensors-$version-upstream_fixes-1.patch

   make CC=$HOST-gcc PREFIX=/usr BUILD_STATIC_LIB=0 \
        sbindir=/usr/bin MANDIR=/usr/share/man DESTDIR=$PKG install

}
