# Description: lm_sensors package provides user-space support for the hardware monitoring drivers in the Linux kernel.
# URL: https://hwmon.wiki.kernel.org/lm_sensors
# License: GPLv2

name=lm-sensors
version=3.4.0
release=1
source=(http://mirror.mini-distribution.io/lm_sensors-$version.tar.bz2)

build()
{
   cd lm_sensors-$version

   make CC=$HOST-gcc PREFIX=/usr BUILD_STATIC_LIB=0 \
        sbindir=/usr/bin MANDIR=/usr/share/man DESTDIR=$PKG install

}
