# Description: WebP image library
# URL: https://developers.google.com/speed/webp
# License: BSD-3

name=libwebp
version=0.4.1
release=1
source=(http://downloads.webmproject.org/releases/webp/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --disable-gl \
               --disable-png \
               --disable-jpeg \
               --disable-tiff \
               --disable-gif \
               --disable-wic

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
