# Description: A free and portable TrueType font rendering engine
# URL: http://www.freetype.org
# License: FTL GPLv2

name=freetype
version=2.6.3
release=1
source=(http://download.savannah.gnu.org/releases/$name/$name-$version.tar.bz2)
depends=zlib

build() {
   cd freetype-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --with-zlib \
               --without-png \
               LDFLAGS="-lz -L$SYSROOT/usr/lib"

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
