# Description: File comparing utilities
# URL: http://www.gnu.org/software/diffutils
# License: GPLv3

name=diffutils
version=3.5
release=1
source=(http://ftp.gnu.org/gnu/$name/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   rm -r $PKG/usr/share/info
}
