# Description: User space IEEE 802.1X/WPA supplicant (wireless client)
# URL: http://hostap.epitest.fi/wpa_supplicant
# License: BSD

name=wpa_supplicant
version=2.5
release=1
source=(http://hostap.epitest.fi/releases/$name-$version.tar.gz
        wpa_supplicant.service
        wpa_supplicant.conf)
depends=(openssl ncurses readline libnl dbus)

build () {

   cd $name-$version/$name

   cp defconfig .config
   echo "BINDIR=/usr/sbin" >> .config
   echo "CONFIG_READLINE=y" >> .config
   echo "CONFIG_DRIVER_NL80211=y" >> .config
   echo "CONFIG_CTRL_IFACE_DBUS_NEW=y" >> .config
   echo "CONFIG_CTRL_IFACE_DBUS_INTRO=y" >> .config
   echo "CONFIG_CTRL_IFACE=y" >> .config
   echo "CONFIG_LIBNL32=y" >> .config
   echo "CONFIG_AP=y" >> .config
   echo "CONFIG_P2P=y" >> .config

   CFLAGS="-I$SYSROOT/usr/include/libnl3" \
   make -j $JOBS CC="$HOST-gcc"

   install -d -m755 $PKG/usr/share/man/man{8,5}
   install doc/docbook/wpa_{background,cli,passphrase,supplicant}.8 $PKG/usr/share/man/man8
   install doc/docbook/wpa_supplicant.conf.5 $PKG/usr/share/man/man5

   install -d -m755 $PKG/usr/sbin
   install wpa_{cli,passphrase,supplicant} $PKG/usr/sbin

   install -d -m755 $PKG/usr/share/dbus-1/system-services
   install -m644 dbus/{fi.epitest.hostap.WPASupplicant.service,fi.w1.wpa_supplicant1.service} $PKG/usr/share/dbus-1/system-services

   install -d -m755 $PKG/etc/dbus-1/system.d
   install -m644 dbus/dbus-wpa_supplicant.conf $PKG/etc/dbus-1/system.d
   install -m644 $SRC/wpa_supplicant.conf $PKG/etc

   install -d -m755 $PKG/etc/systemd/system
   install -m644 $SRC/wpa_supplicant.service $PKG/etc/systemd/system
}
