# Description: userspace RCU (read-copy-update) library.
# URL: http://urcu.so
# License: LGPLv2.1

name=liburcu
version=0.8.5
release=1
source=(http://mirror.mini-distribution.io/userspace-rcu-$version.tar.xz)

build () {
    cd userspace-rcu-$version

    ac_cv_func_malloc_0_nonnull=yes \
    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --disable-static

    make -j $JOBS
    make DESTDIR=$PKG install

    # Cleanup
    rm -r $PKG/usr/share

    # Fix libtool files
    fix_la_files $PKG
}
