# Description: A Linux kernel packet filter control tool
# URL: http://www.iptables.org/

name=iptables
version=1.4.17
release=1
source=(ftp://ftp.netfilter.org/pub/iptables/$name-$version.tar.bz2
        libip6t_NETMAP-link.patch)

build () {
   cd $name-$version

   patch -p1 < $SRC/libip6t_NETMAP-link.patch

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --enable-libipq \

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
