# Description: Official Linux Bluetooth protocol stack
# URL: https://www.bluez.org
# License: GPLv2

name=bluez4
version=4.101
release=1
source=(http://www.kernel.org/pub/linux/bluetooth/bluez-$version.tar.xz)
depends=(systemd glib dbus readline libusb libical)

build() {
   cd bluez-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static \
               --sysconfdir=/etc \
               --enable-pand \
               --disable-usb

   make -j $JOBS
   make DESTDIR=$PKG install

   # Install configuration files
   for FILE in audio input serial network; do
      install -m644 ${FILE}/${FILE}.conf $PKG/etc/bluetooth/${FILE}.conf
   done

   # Fix libtool files
   fix_la_files $PKG
}
