# Description: Library of PNG support functions
# URL: http://www.libpng.org

name=libpng
version=1.5.14
release=1
source=(ftp://ftp.simplesystems.org/pub/$name/png/src/libpng15/$name-$version.tar.xz)
depends=zlib

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
