# Description: Library of PNG support functions
# URL: http://www.libpng.org
# License: ZLIB

name=libpng
version=1.6.15
release=1
source=(ftp://ftp.simplesystems.org/pub/libpng/png/src/history/libpng16/$name-$version.tar.xz)
depends=zlib

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
