# Description: Network sniffer with command line interface
# URL: http://www.tcpdump.org
# License: BSD

name=tcpdump
version=4.7.4
release=1
source=(http://www.tcpdump.org/release/$name-$version.tar.gz)
depends=(libpcap openssl)

build() {
    cd $name-$version
    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --disable-ipv6 \
                ac_cv_linux_vers=2 \
                PCAP_CONFIG=$SYSROOT/usr/bin/pcap-config

    make -j $JOBS
    make DESTDIR=$PKG install

    rm $PKG/usr/sbin/tcpdump.$version
}
