# Description: Pixel manipulation library
# URL: http://xorg.freedesktop.org

name=pixman
version=0.34.0
release=1
source=(http://xorg.freedesktop.org/releases/individual/lib/$name-$version.tar.bz2)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
