# Description: Pixel manipulation library
# URL: http://www.pixman.org

name=pixman
version=0.34.0
release=1
source=(https://www.cairographics.org/releases/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --disable-static

   make -j $JOBS
   make DESTDIR=$PKG install

   # Fix libtool files
   fix_la_files $PKG
}
