# Description: gst-rtsp-server is a library ion top of GStreamer for building an RTSP server 
# URL: http://cgit.freedesktop.org/gstreamer/gst-rtsp-server
# License: LGPLv2

name=gst-rtsp-server
version=1.6.0
release=1
source=(http://gstreamer.freedesktop.org/src/$name/$name-$version.tar.xz)
depends=(glib gstreamer gst-plugins-base)

build()
{
    cd $name-$version

    ./configure --host=$HOST --prefix=/usr

    make -j$JOBS

    make install DESTDIR=$PKG

    # Fix installed la files
    fix_la_files $PKG
}
