# Description: FUSE (Filesystem in Userspace) 
# URL: https://sourceforge.net/projects/fuse/
# License: GPLv2

name=fuse
version=3.2.3
release=1
source=(https://github.com/libfuse/libfuse/releases/download/$name-$version/$name-$version.tar.xz)
depends=(systemd)

build() {
    cd $name-$version

    meson build --prefix=/usr \
                --libdir=/usr/lib \
                --sysconfdir=/etc \
                --localstatedir=/var \
                --cross-file=$CFG/$HOST.meson

#    meson configure build -Dapparmor=false \

    ninja -C build

    DESTDIR=$PKG ninja -C build install

    rm -rf $PKG/etc/
}
