# Description: Packet capture library
# URL:         http://www.tcpdump.org

name=libpcap
version=1.3.0
release=1
source=(http://www.tcpdump.org/release/$name-$version.tar.gz)

build ()
{
    cd $name-$version

    sed -i '/ln [^-][^s]/s/ln/ln -s/' Makefile.in

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --with-pcap=linux

    make -j $JOBS
    make DESTDIR=$PKG install
}
