# Description: Packet capture library
# URL: http://www.tcpdump.org
# License: BSD

name=libpcap
version=1.6.1
release=1
source=(http://www.tcpdump.org/release/$name-$version.tar.gz)
depends=(libusb)

build () {
    cd $name-$version

    install -d $PKG/usr/bin

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --with-pcap=linux \
                --without-libnl

    make -j $JOBS
    make DESTDIR=$PKG install install-shared

    rm $PKG/usr/lib/libpcap.a
}
