# Description: Packet capture library
# URL: http://www.tcpdump.org
# License: BSD

name=libpcap
version=1.8.1
release=1
source=(http://www.tcpdump.org/release/$name-$version.tar.gz
        libpcap-1.6.2-enable_bluetooth-1.patch
        0002-pcap-config-add-SYSROOT-support.patch)
depends=(libusb bluez)

build () {
    cd $name-$version

    patch -p1 -i $SRC/libpcap-1.6.2-enable_bluetooth-1.patch
    patch -p1 -i $SRC/0002-pcap-config-add-SYSROOT-support.patch

    install -d $PKG/usr/bin

    ./configure --build=$BUILD \
                --host=$HOST \
                --prefix=/usr \
                --with-pcap=linux \
                --without-libnl

    make -j $JOBS
    make DESTDIR=$PKG install install-shared

    rm $PKG/usr/lib/libpcap.a
}
