# Description: High performance JPEG library
# URL: http://www.libjpeg-turbo.org
# License: BSD

name=libjpeg-turbo
version=1.5.1
release=1
source=(http://downloads.sourceforge.net/project/libjpeg-turbo/$version/$name-$version.tar.gz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr \
               --mandir=/usr/share/man \
               --disable-static \
               --with-jpeg8

   make -j $JOBS
   make DESTDIR=$PKG install

   # Cleanup
   rm -r $PKG/usr/share/doc

   # Fix libtool files
   fix_la_files $PKG
}
