# Description: A simple TTY terminal I/O application
# URL: https://tio.github.io
# License: GPLv2

name=tio
version=1.19
release=1
source=(https://github.com/$name/$name/releases/download/v$version/$name-$version.tar.xz)

build() {
   cd $name-$version

   ./configure --build=$BUILD \
               --host=$HOST \
               --prefix=/usr

   make -j $JOBS
   make DESTDIR=$PKG install
}
